Algebra_Agent
  type=zip
  out=Agents/
  Agents-Soar_Group/algebra=top
Arithmetic_Agent
  type=zip
  out=Agents/
  Agents-Soar_Group/arithmetic=top
Arithmetic-SMem_Agent
  type=zip
  out=Agents/
  Agents-Soar_Group/arithmetic-smem=top
BlocksWorld_Hierarchical_Lookahead_Agent
  type=zip
  out=Agents/
  Agents-Soar_Group/BW-Hierarchical-LA=top
BlocksWorld_Hierarchical_Agent
  type=zip
  out=Agents/
  Agents-Soar_Group/BW-Hierarchical=top
BlocksWorld_Lookahead_Agent
  type=zip
  out=Agents/
  Agents-Soar_Group/BW-LA=top
BlocksWorld_Hierarchical_State_Evaluation_Agent
  type=zip
  out=Agents/
  Agents-Soar_Group/BW-LA-state-eval=top
BlocksWorld_Subgoaling_Agent
  type=zip
  out=Agents/
  Agents-Soar_Group/BW-Op-Subgoal=top
BlocksWorld_Subgoaling_RL_Agent
  type=zip
  out=Agents/
  Agents-Soar_Group/BW-Op-Subgoal-RL=top
BlocksWorld_RL_Agent
  type=zip
  out=Agents/
  Agents-Soar_Group/BW-RL=top
BlocksWorld_Simple_Agent
  type=zip
  out=Agents/
  Agents-Soar_Group/BW-simple=top
Episodic_Memory_Counting_Agent
  type=zip
  out=Agents/
  Agents-Soar_Group/count-epmem=top
Counting_Agent
  type=zip
  out=Agents/
  Agents-Soar_Group/count-test-files=top
Eight_Puzzle_Agent
  type=zip
  out=Agents/
  Agents-Soar_Group/eight-puzzle=top
Episodic_Memory_Tutorial_Agent
  type=zip
  out=Agents/
  Agents-Soar_Group/epmem-tutorial=top
Fifteen_Puzzle_Agent
  type=zip
  out=Agents/
  Agents-Soar_Group/fifteen-puzzle=top
Graph_Search_Agent
  type=zip
  out=Agents/
  Agents-Soar_Group/graph-search=top
Graph_Search_SMem_Agent
  type=zip
  out=Agents/
  Agents-Soar_Group/graph-search-smem=top
Hello_World_Operator_Agent
  type=zip
  out=Agents/
  Agents-Soar_Group/hello-world-operator=top
Hello_World_Rule_Agent
  type=zip
  out=Agents/
  Agents-Soar_Group/hello-world-rule=top
KB_Agent
  type=zip
  out=Agents/
  Agents-Soar_Group/kb=top
Left_Right_RL_Agent
  type=zip
  out=Agents/
  Agents-Soar_Group/left-right=top
Missionaries_And_Cannibals_Simple_Agent
  type=zip
  out=Agents/
  Agents-Soar_Group/mac=top
Missionaries_And_Cannibals_Planning_Agent
  type=zip
  out=Agents/
  Agents-Soar_Group/mac-planning=top
Reinforcement_Learning_Unit_Test_Agent
  type=zip
  out=Agents/
  Agents-Soar_Group/rl-unit=top
Semantic_Memory_Tutorial_Agent
  type=zip
  out=Agents/
  Agents-Soar_Group/smem-tutorial=top
Tower_Of_Hanoi_Recursive_Agent
  type=zip
  out=Agents/
  Agents-Soar_Group/towers-of-hanoi-recursive=top
Tower_Of_Hanoi_Simple_Agent
  type=zip
  out=Agents/
  Agents-Soar_Group/towers-of-hanoi-simple=top
Water_Jug_Hierarchical_Agent
  type=zip
  out=Agents/
  Agents-Soar_Group/water-jug-hierarchy=top
Water_Jug_Look_Ahead_Agent
  type=zip
  out=Agents/
  Agents-Soar_Group/water-jug-look-ahead=top
Water_Jug_Reinforcement_Learning_Agent
  type=zip
  out=Agents/
  Agents-Soar_Group/water-jug-rl=top
Water_Jug_Simple_Agent
  type=zip
  out=Agents/
  Agents-Soar_Group/water-jug-simple=top
Water_Jug_Tie_Agent
  type=zip
  out=Agents/
  Agents-Soar_Group/water-jug-tie=top
SoarManual
  type=copy
  out=Documentation/
  Release-Support/pdf/SoarManual.pdf=top
SoarTutorial
  type=copy
  out=Documentation/
  Release-Support/pdf/Soar Tutorial Part 1.pdf=SoarTutorial
  Release-Support/pdf/Soar Tutorial Part 2.pdf=SoarTutorial
  Release-Support/pdf/Soar Tutorial Part 3.pdf=SoarTutorial
  Release-Support/pdf/Soar Tutorial Part 4.pdf=SoarTutorial
  Release-Support/pdf/Soar Tutorial Part 5.pdf=SoarTutorial
  Release-Support/pdf/Soar Tutorial Part 6.pdf=SoarTutorial
  Release-Support/pdf/Soar Tutorial Part 7 - RL.pdf=SoarTutorial
  Release-Support/pdf/Soar Tutorial Part 8 - SMem.pdf=SoarTutorial
  Release-Support/pdf/Soar Tutorial Part 9 - EpMem.pdf=SoarTutorial
Episodic_Memory_Sizer
    type=zip
    out=AgentDevelopmentTools/
    Other-Agent-Development-Tools/epmem-size=top
QuickLink
    type=zip
    out=AgentDevelopmentTools/
    Other-Agent-Development-Tools/QuickLink=top
State2Dot
    type=zip
    out=AgentDevelopmentTools/
    Other-Agent-Development-Tools/State2Dot=top
UltraEdit_Soar_Formatting_Wordfile
    type=zip
    out=AgentDevelopmentTools/
    Other-Agent-Development-Tools/UltraEdit_Wordfile=top
VisualSoar_Source
    type=zip
    out=AgentDevelopmentTools/
    VisualSoar=top
Vim_Soar_Formatting_Plugin
    type=zip
    out=AgentDevelopmentTools/
    Other-Agent-Development-Tools/vimplugin=top
SoarQnA
    type=zip
    out=Domains/
    Domains-SoarQnA=top
SoarTextIO
    type=zip
    out=Domains/
    Domains-SoarTextIO=top
WordNet
    type=zip
    out=Domains/
    Domains-WordNet=top
WordNet_With_Parse_Trees
    type=zip
    out=Domains/
    Domains-WordNet-with-Parse-Trees=top
CSharp_Interface_Example
    type=zip
    out=Examples-and-Unsupported/
    Examples-and-Unsupported/CSharp=top
PHP_Interface_Example
    type=zip
    out=Examples-and-Unsupported/
    Examples-and-Unsupported/PHP=top
Python_Interface_Example
    type=zip
    out=Examples-and-Unsupported/
    Examples-and-Unsupported/Soar_Exp=top
Soar_Scratch_Pad_Example
    type=zip
    out=Examples-and-Unsupported/
    Examples-and-Unsupported/SoarScratchPad=top
Tower_Of_Hanoi_SML_Example
    type=zip
    out=Examples-and-Unsupported/
    Examples-and-Unsupported/TOHSML=top
Soar_Filter_C_Example
    type=zip
    out=Examples-and-Unsupported/
    Examples-and-Unsupported/FilterC=top
Soar_Filter_Tcl_Example
    type=zip
    out=Examples-and-Unsupported/
    Examples-and-Unsupported/FilterTcl=top
Java_Missionaries_and_Cannibals_Example
    type=zip
    out=Examples-and-Unsupported/
    Examples-and-Unsupported/JavaMissionaries=top
Java_Tower_of_Hanoi_Example
    type=zip
    out=Examples-and-Unsupported/
    Examples-and-Unsupported/JavaTOH=top
LoggerJava_Example
    type=zip
    out=Examples-and-Unsupported/
    Examples-and-Unsupported/LoggerJava=top
LoggerWinC_Example
    type=zip
    out=Examples-and-Unsupported/
    Examples-and-Unsupported/LoggerWinC=top
RL_Command_Line_Interface_Example
    type=zip
    out=Examples-and-Unsupported/
    Examples-and-Unsupported/RlCli=top
Soar_Obfuscator
    type=zip
    out=Examples-and-Unsupported/
    Examples-and-Unsupported/SoarObfuscator=top
Working_Memory_Activation_Tracker_Example
    type=zip
    out=Examples-and-Unsupported/
    Examples-and-Unsupported/WMActivationTracker=top
RoomsWorld_9.6.0
  type=zip
  out=Examples-and-Unsupported/
  Domains-RoomsWorld=RoomsWorld
InfiniteMario-9.6.0
  type=zip
  out=Domains/
  Domains-InfiniteMario=InfiniteMario/
DiceQnA
  type=zip
  out=Domains/
  Domains-DiceQnA=DiceQnA/
Dice
  type=zip
  out=Domains/
  Domains-Dice=Dice/
GGP
  type=zip
  out=Domains/
  Domains-General-Game-Playing=GGP/
PDDL
  type=zip
  out=Domains/
  Domains-Planning-Domain-Definition-Language=PDDL/
SoarSuite_9.6.0
  type=multiplatform-zip
  out=SoarSuite/
  Release-Support/Shuffler_Input/COMPILE_DIR/out/libSoar.DLL_EXTENSION=bin/PLATFORM_DIR
  Release-Support/Shuffler_Input/COMPILE_DIR/out/libJava_sml_ClientInterface.DLL_EXTENSION=bin/PLATFORM_DIR
  Release-Support/Shuffler_Input/COMPILE_DIR/out/Python_sml_ClientInterface.py=bin/PLATFORM_DIR
  Release-Support/Shuffler_Input/COMPILE_DIR/out/_Python_sml_ClientInterface.DLL_EXTENSION=bin/PLATFORM_DIR
  Release-Support/Shuffler_Input/COMPILE_DIR/out/libTcl_sml_ClientInterface.DLL_EXTENSION=bin/PLATFORM_DIR
  Release-Support/Shuffler_Input/COMPILE_DIR/out/libtclsoarlib.DLL_EXTENSION=bin/PLATFORM_DIR
  Release-Support/Shuffler_Input/COMPILE_DIR/out/pkgIndex.tcl=bin/PLATFORM_DIR
  Release-Support/Shuffler_Input/COMPILE_DIR/out/java/swt.jar=bin/PLATFORM_DIR
  Release-Support/Shuffler_Input/COMPILE_DIR/out/soar.EXECUTABLE=bin/PLATFORM_DIR
  Release-Support/Shuffler_Input/COMPILE_DIR/out/UnitTests.EXECUTABLE=bin/PLATFORM_DIR
  Release-Support/Shuffler_Input/COMPILE_DIR/out/svs_viewer.EXECUTABLE=bin/PLATFORM_DIR
  Release-Support/Shuffler_Input/COMPILE_DIR/out/SoarJavaDebugger.jar=bin
  Release-Support/Shuffler_Input/COMPILE_DIR/out/java/jcommon-1.0.10.jar=bin/java
  Release-Support/Shuffler_Input/COMPILE_DIR/out/java/jfreechart-1.0.6-swt.jar=bin/java
  Release-Support/Shuffler_Input/COMPILE_DIR/out/java/jfreechart-1.0.6.jar=bin/java
  Release-Support/Shuffler_Input/COMPILE_DIR/out/java/sml.jar=bin/java
  Release-Support/Shuffler_Input/COMPILE_DIR/out/java/soar-debugger-api.jar=bin/java
  Release-Support/Shuffler_Input/COMPILE_DIR/out/java/soar-debugger.jar=bin/java
  Release-Support/Shuffler_Input/COMPILE_DIR/out/java/soar-smljava.jar=bin/java
  Release-Support/Shuffler_Input/COMPILE_DIR/out/java/swtgraphics2d.jar=bin/java
  Release-Support/Shuffler_Input/COMPILE_DIR/out/tcl=bin/tcl
  Release-Support/Shuffler_Input/COMPILE_DIR/out/settings.soar=bin
  Release-Support/Shuffler_Input/jars/VisualSoar.jar=bin
  Agents-Soar_Group/default=Agents/default
  Release-Support/scripts/SoarCLI.LAUNCH_EXTENSION=top
  Release-Support/scripts/SoarJavaDebugger.LAUNCH_EXTENSION=top
  Release-Support/scripts/VisualSoar.LAUNCH_EXTENSION=top
  Release-Support/pdf/SoarManual.pdf=Documentation
  Release-Support/txt/Building_Soar.txt=Documentation
  Release-Support/txt/Release_Notes_9.6.0.txt=Documentation
  Release-Support/txt/9.6.0_Command_Line_Options.txt=Documentation
  Release-Support/txt/9.6.0_UI_Changes.txt=Documentation
  SoarSuite/Tcl/TclSoarLib_README.txt=Documentation
  Release-Support/txt/license.txt=top
  Release-Support/Shuffler_Input/COMPILE_DIR/out/concrt140.dll=bin/PLATFORM_DIR^
  Release-Support/Shuffler_Input/COMPILE_DIR/out/CSharp_sml_ClientInterface.dll=bin/PLATFORM_DIR^
  Release-Support/Shuffler_Input/COMPILE_DIR/out/msvcp140.dll=bin/PLATFORM_DIR^
  Release-Support/Shuffler_Input/COMPILE_DIR/out/sml_csharp.dll=bin/PLATFORM_DIR^
  Release-Support/Shuffler_Input/COMPILE_DIR/out/Soar.lib=bin/PLATFORM_DIR^
  Release-Support/Shuffler_Input/COMPILE_DIR/out/Tcl_sml_ClientInterface.exp=bin/PLATFORM_DIR^
  Release-Support/Shuffler_Input/COMPILE_DIR/out/Tcl_sml_ClientInterface.lib=bin/PLATFORM_DIR^
  Release-Support/Shuffler_Input/COMPILE_DIR/out/vccorlib140.dll=bin/PLATFORM_DIR^
  Release-Support/Shuffler_Input/COMPILE_DIR/out/vcruntime140.dll=bin/PLATFORM_DIR^
SoarTutorial_9.6.0
  type=multiplatform-zip
  out=SoarSuite/
  Release-Support/Shuffler_Input/COMPILE_DIR/out/libSoar.DLL_EXTENSION=bin/PLATFORM_DIR
  Release-Support/Shuffler_Input/COMPILE_DIR/out/libJava_sml_ClientInterface.DLL_EXTENSION=bin/PLATFORM_DIR
  Release-Support/Shuffler_Input/COMPILE_DIR/out/libTcl_sml_ClientInterface.DLL_EXTENSION=bin/PLATFORM_DIR
  Release-Support/Shuffler_Input/COMPILE_DIR/out/libtclsoarlib.DLL_EXTENSION=bin/PLATFORM_DIR
  Release-Support/Shuffler_Input/COMPILE_DIR/out/pkgIndex.tcl=bin/PLATFORM_DIR
  Release-Support/Shuffler_Input/COMPILE_DIR/out/java/swt.jar=bin/PLATFORM_DIR
  Release-Support/Shuffler_Input/COMPILE_DIR/out/soar.EXECUTABLE=bin/PLATFORM_DIR
  Release-Support/Shuffler_Input/COMPILE_DIR/out/UnitTests.EXECUTABLE=bin/PLATFORM_DIR
  Release-Support/Shuffler_Input/COMPILE_DIR/out/svs_viewer.EXECUTABLE=bin/PLATFORM_DIR
  Release-Support/Shuffler_Input/COMPILE_DIR/out/SoarJavaDebugger.jar=bin
  Release-Support/Shuffler_Input/COMPILE_DIR/out/java/jcommon-1.0.10.jar=bin/java
  Release-Support/Shuffler_Input/COMPILE_DIR/out/java/jfreechart-1.0.6-swt.jar=bin/java
  Release-Support/Shuffler_Input/COMPILE_DIR/out/java/jfreechart-1.0.6.jar=bin/java
  Release-Support/Shuffler_Input/COMPILE_DIR/out/java/sml.jar=bin/java
  Release-Support/Shuffler_Input/COMPILE_DIR/out/java/soar-debugger-api.jar=bin/java
  Release-Support/Shuffler_Input/COMPILE_DIR/out/java/soar-debugger.jar=bin/java
  Release-Support/Shuffler_Input/COMPILE_DIR/out/java/soar-smljava.jar=bin/java
  Release-Support/Shuffler_Input/COMPILE_DIR/out/java/swtgraphics2d.jar=bin/java
  Release-Support/Shuffler_Input/jars/Eaters_TankSoar.jar=bin
  Release-Support/Shuffler_Input/jars/commons-logging-1.1.1.jar=bin/java
  Release-Support/Shuffler_Input/jars/log4j-1.2.15.jar=bin/java
  Release-Support/Shuffler_Input/jars/stopwatch-0.4-with-deps.jar=bin/java
  Release-Support/Shuffler_Input/jars/VisualSoar.jar=bin
  Release-Support/Shuffler_Input/COMPILE_DIR/out/settings.soar=bin
  Release-Support/scripts/SoarCLI.LAUNCH_EXTENSION=top
  Release-Support/scripts/SoarJavaDebugger.LAUNCH_EXTENSION=top
  Release-Support/scripts/VisualSoar.LAUNCH_EXTENSION=top
  Release-Support/scripts/Eaters.LAUNCH_EXTENSION=top
  Release-Support/scripts/TankSoar.LAUNCH_EXTENSION=top
  Release-Support/pdf/SoarManual.pdf=Documentation
  Release-Support/Shuffler_Input/COMPILE_DIR/out/tcl=bin/tcl
  Release-Support/txt/9.6.0_Command_Line_Options.txt=Documentation
  Release-Support/txt/license.txt=top
  Release-Support/txt/Agents_readme.txt=Agents/
  Release-Support/pdf/Soar Tutorial Part 1.pdf=Documentation
  Release-Support/pdf/Soar Tutorial Part 2.pdf=Documentation
  Release-Support/pdf/Soar Tutorial Part 3.pdf=Documentation
  Release-Support/pdf/Soar Tutorial Part 4.pdf=Documentation
  Release-Support/pdf/Soar Tutorial Part 5.pdf=Documentation
  Release-Support/pdf/Soar Tutorial Part 6.pdf=Documentation
  Release-Support/pdf/Soar Tutorial Part 7 - RL.pdf=Documentation
  Release-Support/pdf/Soar Tutorial Part 8 - SMem.pdf=Documentation
  Release-Support/pdf/Soar Tutorial Part 9 - EpMem.pdf=Documentation
  Agents-Soar_Group/arithmetic=Agents/arithmetic
  Agents-Soar_Group/BW-RL=Agents/BW-RL
  Agents-Soar_Group/BW-Hierarchical-LA=Agents/BW-Hierarchical-LA
  Agents-Soar_Group/BW-Hierarchical=Agents/BW-Hierarchical
  Agents-Soar_Group/BW-LA-state-eval=Agents/BW-LA-state-eval
  Agents-Soar_Group/BW-LA=Agents/BW-LA
  Agents-Soar_Group/BW-Op-Subgoal-RL=Agents/BW-Op-Subgoal-RL
  Agents-Soar_Group/BW-Op-Subgoal=Agents/BW-Op-Subgoal
  Agents-Soar_Group/BW-Simple=Agents/BW-Simple
  Agents-Soar_Group/BW-SoarManual=Agents/BW-SoarManual
  Agents-Soar_Group/default=Agents/default
  Agents-Soar_Group/eight-puzzle=Agents/eight-puzzle
  Agents-Soar_Group/epmem-tutorial=Agents/epmem-tutorial
  Agents-Soar_Group/fifteen-puzzle=Agents/fifteen-puzzle
  Agents-Soar_Group/hello-world-operator=Agents/hello-world-operator
  Agents-Soar_Group/hello-world-rule=Agents/hello-world-rule
  Agents-Soar_Group/left-right=Agents/left-right
  Agents-Soar_Group/mac-planning=Agents/mac-planning
  Agents-Soar_Group/mac=Agents/mac
  Agents-Soar_Group/smem-tutorial=Agents/smem-tutorial
  Agents-Soar_Group/towers-of-hanoi-recursive=Agents/towers-of-hanoi-recursive
  Agents-Soar_Group/towers-of-hanoi-simple=Agents/towers-of-hanoi-simple
  Agents-Soar_Group/water-jug-hierarchy=Agents/water-jug-hierarchy
  Agents-Soar_Group/water-jug-look-ahead=Agents/water-jug-look-ahead
  Agents-Soar_Group/water-jug-rl=Agents/water-jug-rl
  Agents-Soar_Group/water-jug-simple=Agents/water-jug-simple
  Agents-Soar_Group/water-jug-tie=Agents/water-jug-tie
  Domains-Eaters-TankSoar/agents/eaters=Agents/Eaters
  Domains-Eaters-TankSoar/agents/tanksoar=Agents/TankSoar
  Domains-Eaters-TankSoar/config/eaters.cnf=config
  Domains-Eaters-TankSoar/config/maps/eaters=config/maps/eaters
  Domains-Eaters-TankSoar/config/maps/tanksoar=config/maps/tanksoar
  Domains-Eaters-TankSoar/config/tanksoar.cnf=config
  Release-Support/Shuffler_Input/COMPILE_DIR/out/concrt140.dll=bin/PLATFORM_DIR^
  Release-Support/Shuffler_Input/COMPILE_DIR/out/msvcp140.dll=bin/PLATFORM_DIR^
  Release-Support/Shuffler_Input/COMPILE_DIR/out/Soar.lib=bin/PLATFORM_DIR^
  Release-Support/Shuffler_Input/COMPILE_DIR/out/Tcl_sml_ClientInterface.exp=bin/PLATFORM_DIR^
  Release-Support/Shuffler_Input/COMPILE_DIR/out/Tcl_sml_ClientInterface.lib=bin/PLATFORM_DIR^
  Release-Support/Shuffler_Input/COMPILE_DIR/out/vccorlib140.dll=bin/PLATFORM_DIR^
  Release-Support/Shuffler_Input/COMPILE_DIR/out/vcruntime140.dll=bin/PLATFORM_DIR^
SoarSuite_9.6.0-source
  type=zip
  out=SoarSuite/
  SoarSuite/Core=Core
  SoarSuite/Java=Java
  SoarSuite/scons=scons
  SoarSuite/Tcl=Tcl
  SoarSuite/PerformanceTests=PerformanceTests
  SoarSuite/SoarCLI=SoarCLI
  SoarSuite/UnitTests=UnitTests
  SoarSuite/build_ios.sh=top
  SoarSuite/build_lsb.sh=top
  SoarSuite/build.bat=top
  SoarSuite/SConstruct=top
  Release-Support/pdf/SoarManual.pdf=Documentation
  Release-Support/txt/Building_Soar.txt=Documentation
  Release-Support/txt/Release_Notes_9.6.0.txt=Documentation
  Release-Support/txt/9.6.0_Command_Line_Options.txt=Documentation
  Release-Support/txt/9.6.0_UI_Changes.txt=Documentation
  Release-Support/txt/license.txt=top