SoarManual
  type=copy
  out=Documentation/
  Release-Support/pdf/SoarManual.pdf=top
SoarTutorial
  type=copy
  out=Documentation/
  Release-Support/pdf/Soar Tutorial Part 1.pdf=SoarTutorial
  Release-Support/pdf/Soar Tutorial Part 2.pdf=SoarTutorial
  Release-Support/pdf/Soar Tutorial Part 3.pdf=SoarTutorial
  Release-Support/pdf/Soar Tutorial Part 4.pdf=SoarTutorial
  Release-Support/pdf/Soar Tutorial Part 5.pdf=SoarTutorial
  Release-Support/pdf/Soar Tutorial Part 6.pdf=SoarTutorial
  Release-Support/pdf/Soar Tutorial Part 7 - RL.pdf=SoarTutorial
  Release-Support/pdf/Soar Tutorial Part 8 - SMem.pdf=SoarTutorial
  Release-Support/pdf/Soar Tutorial Part 9 - EpMem.pdf=SoarTutorial
SoarTutorial_9.6.0
  type=multiplatform-zip
  out=SoarSuite/
  Release-Support/Shuffler_Input/jars/VisualSoar.jar=bin
  Release-Support/Shuffler_Input/COMPILE_DIR/out/libSoar.DLL_EXTENSION=bin
  Release-Support/Shuffler_Input/COMPILE_DIR/out/libJava_sml_ClientInterface.DLL_EXTENSION=bin
  Release-Support/Shuffler_Input/COMPILE_DIR/out/SoarJavaDebugger.jar=bin
  Release-Support/Shuffler_Input/COMPILE_DIR/out/java=bin/java
  Release-Support/Shuffler_Input/COMPILE_DIR/out/libTcl_sml_ClientInterface.DLL_EXTENSION=bin
  Release-Support/Shuffler_Input/COMPILE_DIR/out/libtclsoarlib.DLL_EXTENSION=bin
  Release-Support/Shuffler_Input/COMPILE_DIR/out/pkgIndex.tcl=bin
  Release-Support/Shuffler_Input/COMPILE_DIR/out/tcl=bin/tcl
  Release-Support/txt/Agents_readme.txt=Agents/
  Release-Support/txt/9.6.0_Command_Line_Options.txt=Documentation
  Release-Support/txt/9.6.0_UI_Changes.txt=Documentation
  Release-Support/txt/Release_Notes_9.6.0.txt=Documentation
  Release-Support/pdf/Soar Tutorial Part 1.pdf=Documentation
  Release-Support/pdf/Soar Tutorial Part 2.pdf=Documentation
  Release-Support/pdf/Soar Tutorial Part 3.pdf=Documentation
  Release-Support/pdf/Soar Tutorial Part 4.pdf=Documentation
  Release-Support/pdf/Soar Tutorial Part 5.pdf=Documentation
  Release-Support/pdf/Soar Tutorial Part 6.pdf=Documentation
  Release-Support/pdf/Soar Tutorial Part 7 - RL.pdf=Documentation
  Release-Support/pdf/Soar Tutorial Part 8 - SMem.pdf=Documentation
  Release-Support/pdf/Soar Tutorial Part 9 - EpMem.pdf=Documentation
  Release-Support/pdf/SoarManual.pdf=Documentation
  SoarSuite/Tcl/TclSoarLib_README.txt=Documentation
  Agents/arithmetic=Agents/arithmetic
  Agents/blocks-world-RL=Agents/blocks-world-RL
  Agents/blocks-world-hierachical-lookahead=Agents/blocks-world-hierachical-lookahead
  Agents/blocks-world-hierarchical=Agents/blocks-world-hierarchical
  Agents/blocks-world-lookahead-state-evaluation=Agents/blocks-world-lookahead-state-evaluation
  Agents/blocks-world-lookahead=Agents/blocks-world-lookahead
  Agents/blocks-world-operator-subgoaling-RL=Agents/blocks-world-operator-subgoaling-RL
  Agents/blocks-world-operator-subgoaling=Agents/blocks-world-operator-subgoaling
  Agents/blocks-world-simple=Agents/blocks-world-simple
  Agents/default=Agents/default
  Agents/eight-puzzle=Agents/eight-puzzle
  Agents/epmem-tutorial=Agents/epmem-tutorial
  Agents/fifteen-puzzle=Agents/fifteen-puzzle
  Agents/hello-world-operator=Agents/hello-world-operator
  Agents/hello-world-rule=Agents/hello-world-rule
  Agents/left-right=Agents/left-right
  Agents/mac-planning=Agents/mac-planning
  Agents/mac=Agents/mac
  Agents/smem-tutorial=Agents/smem-tutorial
  Agents/towers-of-hanoi-recursive=Agents/towers-of-hanoi-recursive
  Agents/towers-of-hanoi-simple=Agents/towers-of-hanoi-simple
  Agents/water-jug-hierarchy=Agents/water-jug-hierarchy
  Agents/water-jug-look-ahead=Agents/water-jug-look-ahead
  Agents/water-jug-rl=Agents/water-jug-rl
  Agents/water-jug-simple=Agents/water-jug-simple
  Agents/water-jug-tie=Agents/water-jug-tie
  Release-Support/Shuffler_Input/jars/Eaters_TankSoar.jar=bin
  Domains-Eaters-TankSoar/agents/eaters=Agents/Eaters
  Domains-Eaters-TankSoar/agents/tanksoar=Agents/TankSoar
  Domains-Eaters-TankSoar/config/eaters.cnf=config
  Domains-Eaters-TankSoar/config/maps/eaters=config/maps/eaters
  Domains-Eaters-TankSoar/config/maps/tanksoar=config/maps/tanksoar
  Domains-Eaters-TankSoar/config/tanksoar.cnf=config
  Release-Support/Shuffler_Input/jars/commons-logging-1.1.1.jar=bin/java
  Release-Support/Shuffler_Input/jars/log4j-1.2.15.jar=bin/java
  Release-Support/Shuffler_Input/jars/stopwatch-0.4-with-deps.jar=bin/java
  Release-Support/scripts/RELEASE_DIR/Eaters.LAUNCH_EXTENSION=top
  Release-Support/scripts/RELEASE_DIR/SoarJavaDebugger.LAUNCH_EXTENSION=top
  Release-Support/scripts/RELEASE_DIR/TankSoar.LAUNCH_EXTENSION=top
  Release-Support/scripts/RELEASE_DIR/VisualSoar.LAUNCH_EXTENSION=top
TankSoar_9.6.0
  type=multiplatform-zip
  out=Domains/
  Release-Support/scripts/RELEASE_DIR/TankSoar.LAUNCH_EXTENSION=top
  Release-Support/Shuffler_Input/jars/Eaters_TankSoar.jar=bin
  Release-Support/Shuffler_Input/COMPILE_DIR/out/libJava_sml_ClientInterface.DLL_EXTENSION=bin
  Release-Support/Shuffler_Input/COMPILE_DIR/out/libSoar.DLL_EXTENSION=bin
  Release-Support/Shuffler_Input/COMPILE_DIR/out/java/soar-debugger.jar=bin/java
  Release-Support/Shuffler_Input/COMPILE_DIR/out/java/soar-debugger-api.jar=bin/java
  Release-Support/Shuffler_Input/COMPILE_DIR/out/java/soar-smljava.jar=bin/java
  Release-Support/Shuffler_Input/COMPILE_DIR/out/SoarJavaDebugger.jar=bin
  Release-Support/Shuffler_Input/COMPILE_DIR/out/java/swt.jar=bin/java
  Release-Support/Shuffler_Input/COMPILE_DIR/out/java/sml.jar=bin/java
  Release-Support/Shuffler_Input/jars/stopwatch-0.4-with-deps.jar=bin/java
  Release-Support/Shuffler_Input/jars/commons-logging-1.1.1.jar=bin/java
  Release-Support/Shuffler_Input/jars/log4j-1.2.15.jar=bin/java
  Domains-Eaters-TankSoar/agents/tanksoar=agents/
  Domains-Eaters-TankSoar/config/tanksoar.cnf=config
  Domains-Eaters-TankSoar/config/maps/tanksoar=config/maps/tanksoar
Eaters_9.6.0
  type=multiplatform-zip
  out=Domains/
  Release-Support/scripts/RELEASE_DIR/Eaters.LAUNCH_EXTENSION=top
  Release-Support/Shuffler_Input/jars/Eaters_TankSoar.jar=bin
  Release-Support/Shuffler_Input/COMPILE_DIR/out/libJava_sml_ClientInterface.DLL_EXTENSION=bin
  Release-Support/Shuffler_Input/COMPILE_DIR/out/libSoar.DLL_EXTENSION=bin
  Release-Support/Shuffler_Input/COMPILE_DIR/out/java/soar-debugger.jar=bin/java
  Release-Support/Shuffler_Input/COMPILE_DIR/out/java/soar-debugger-api.jar=bin/java
  Release-Support/Shuffler_Input/COMPILE_DIR/out/java/soar-smljava.jar=bin/java
  Release-Support/Shuffler_Input/COMPILE_DIR/out/SoarJavaDebugger.jar=bin
  Release-Support/Shuffler_Input/COMPILE_DIR/out/java/swt.jar=bin/java
  Release-Support/Shuffler_Input/COMPILE_DIR/out/java/sml.jar=bin/java
  Release-Support/Shuffler_Input/jars/stopwatch-0.4-with-deps.jar=bin/java
  Release-Support/Shuffler_Input/jars/commons-logging-1.1.1.jar=bin/java
  Release-Support/Shuffler_Input/jars/log4j-1.2.15.jar=bin/java
  Domains-Eaters-TankSoar/agents/eaters=agents/
  Domains-Eaters-TankSoar/config/eaters.cnf=config
  Domains-Eaters-TankSoar/config/maps/eaters=config/maps/eaters
SoarSuite_9.6.0
  type=multiplatform-zip
  out=SoarSuite/
  Release-Support/Shuffler_Input/COMPILE_DIR/out=bin
  Release-Support/Shuffler_Input/jars/VisualSoar.jar=bin
  Agents/default=Agents/default
  Release-Support/scripts/RELEASE_DIR/SoarJavaDebugger.LAUNCH_EXTENSION=top
  Release-Support/scripts/RELEASE_DIR/VisualSoar.LAUNCH_EXTENSION=top
  Release-Support/pdf/SoarManual.pdf=Documentation
  SoarSuite/Tcl/TclSoarLib_README.txt=Documentation
  Release-Support/txt/Building_Soar.txt=Documentation
  Release-Support/txt/Release_Notes_9.6.0.txt=Documentation
  Release-Support/txt/9.6.0_Command_Line_Options.txt=Documentation
  Release-Support/txt/9.6.0_UI_Changes.txt=Documentation
  Release-Support/txt/license.txt=top
SoarSuite_9.6.0-source
  type=zip
  out=SoarSuite/
  SoarSuite/Core=Core
  SoarSuite/Java=Java
  SoarSuite/MinCLI=MinCLI
  SoarSuite/scons=scons
  SoarSuite/SoarCLI=SoarCLI
  SoarSuite/Tcl=Tcl
  SoarSuite/Tests=Tests
  SoarSuite/build_ios.sh=top
  SoarSuite/build_lsb.sh=top
  SoarSuite/build.bat=top
  SoarSuite/SConstruct=top
  Release-Support/pdf/SoarManual.pdf=Documentation
  Release-Support/txt/9.6.0_Command_Line_Options.txt=Documentation
  Release-Support/txt/9.6.0_UI_Changes.txt=Documentation
  Release-Support/txt/Building_Soar.txt=top
  Release-Support/txt/license.txt=top
  Release-Support/txt/Release_Notes_9.6.0.txt=Documentation
  Release-Support/Shuffler_Input/jars/VisualSoar.jar=bin
RoomsWorld_9.6.0
  type=multiplatform-zip
  out=Domains/
  Release-Support/scripts/RELEASE_DIR/RoomsWorld.LAUNCH_EXTENSION=top
  Release-Support/Shuffler_Input/COMPILE_DIR/soar_robot_server=top
InfiniteMario-9.6.0
  type=zip
  out=Domains/
  Domains-InfiniteMario=InfiniteMario/