SoarTutorial_9.3.3
  type=multiplatform-zip
  out=SoarSuite/
  # Missing: PythonCLI.py
  # Missing: TestPythonSML.py, (joseph will re-add)
  Release/Shuffler_Input/jars/VisualSoar.jar=bin
  Release/Shuffler_Input/COMPILE_DIR/out/libJava_sml_ClientInterface.DLL_EXTENSION=bin
  Release/Shuffler_Input/COMPILE_DIR/out/libSoar.DLL_EXTENSION=bin
  Release/Shuffler_Input/COMPILE_DIR/out/SoarJavaDebugger.jar=bin
  Release/Shuffler_Input/COMPILE_DIR/out/java=bin/java
  Documentation/Agents_readme.txt=Agents/
  Documentation/pdf/Soar Tutorial Part 1.pdf=Documentation
  Documentation/pdf/Soar Tutorial Part 2.pdf=Documentation
  Documentation/pdf/Soar Tutorial Part 3.pdf=Documentation
  Documentation/pdf/Soar Tutorial Part 4.pdf=Documentation
  Documentation/pdf/Soar Tutorial Part 5.pdf=Documentation
  Documentation/pdf/Soar Tutorial Part 6.pdf=Documentation
  Documentation/pdf/Soar Tutorial Part 7 - RL.pdf=Documentation
  Documentation/pdf/Soar Tutorial Part 8 - SMem.pdf=Documentation
  Documentation/pdf/Soar Tutorial Part 9 - EpMem.pdf=Documentation
  Documentation/pdf/SoarManual.pdf=Documentation
  Agents/arithmetic=Agents/arithmetic
  Agents/blocks-world-RL=Agents/blocks-world-RL
  Agents/blocks-world-hierachical-lookahead=Agents/blocks-world-hierachical-lookahead
  Agents/blocks-world-hierarchical=Agents/blocks-world-hierarchical
  Agents/blocks-world-lookahead-state-evaluation=Agents/blocks-world-lookahead-state-evaluation
  Agents/blocks-world-lookahead=Agents/blocks-world-lookahead
  Agents/blocks-world-operator-subgoaling-RL=Agents/blocks-world-operator-subgoaling-RL
  Agents/blocks-world-operator-subgoaling=Agents/blocks-world-operator-subgoaling
  Agents/blocks-world-simple=Agents/blocks-world-simple
  Agents/default=Agents/default
  Agents/eight-puzzle=Agents/eight-puzzle
  Agents/epmem-tutorial=Agents/epmem-tutorial
  Agents/fifteen-puzzle=Agents/fifteen-puzzle
  Agents/hello-world-operator=Agents/hello-world-operator
  Agents/hello-world-rule=Agents/hello-world-rule
  Agents/left-right=Agents/left-right
  Agents/mac-planning=Agents/mac-planning
  Agents/mac=Agents/mac
  Agents/smem-tutorial=Agents/smem-tutorial
  Agents/towers-of-hanoi-recursive=Agents/towers-of-hanoi-recursive
  Agents/towers-of-hanoi-simple=Agents/towers-of-hanoi-simple
  Agents/water-jug-hierarchy=Agents/water-jug-hierarchy
  Agents/water-jug-look-ahead=Agents/water-jug-look-ahead
  Agents/water-jug-rl=Agents/water-jug-rl
  Agents/water-jug-simple=Agents/water-jug-simple
  Agents/water-jug-tie=Agents/water-jug-tie
  Release/Shuffler_Input/jars/Eaters_TankSoar.jar=bin
  Domains/Eaters_TankSoar/agents/eaters=Agents/Eaters
  Domains/Eaters_TankSoar/agents/tanksoar=Agents/TankSoar
  Domains/Eaters_TankSoar/config/eaters.cnf=config
  Domains/Eaters_TankSoar/config/maps/eaters=config/maps/eaters
  Domains/Eaters_TankSoar/config/maps/tanksoar=config/maps/tanksoar
  Domains/Eaters_TankSoar/config/tanksoar.cnf=config
  Release/Shuffler_Input/jars/commons-logging-1.1.1.jar=bin/java
  Release/Shuffler_Input/jars/log4j-1.2.15.jar=bin/java
  Release/Shuffler_Input/jars/stopwatch-0.4-with-deps.jar=bin/java
  Release/scripts/RELEASE_DIR/Eaters.LAUNCH_EXTENSION=top
  Release/scripts/RELEASE_DIR/SoarJavaDebugger.LAUNCH_EXTENSION=top
  Release/scripts/RELEASE_DIR/TankSoar.LAUNCH_EXTENSION=top
  Release/scripts/RELEASE_DIR/VisualSoar.LAUNCH_EXTENSION=top